exports.constants = {
	admin: {
		name: "admin",
		email: "admin@admin.com"
	},
	confirmEmails: {
		from : "no-reply@test-app.com"
	},
	user:{
		invalid_Payload:"invalid Payload",
		USER_RECORDS_INSERTED:"USER_RECORDS_INSERTED",
		USER_ALREADY_EXISTED:"USER_ALREADY_EXISTED",
		USER_RECORDS_NOT_INSERTED:"USER_RECORDS_NOT_INSERTED",
		USER_NOT_FOUND:"USER_NOT_FOUND",
		USERS_RECORDS_NOT_FOUND:"USERS_RECORDS_NOT_FOUND",
		USERS_RECORDS_FOUND:"USERS_RECORDS_FOUND",
		USER_PASSWORD_NOT_MATCHING:"USER_PASSWORD_NOT_MATCHING",
		USER_NEW_PASSWORD_NOT_INSERTED:"USER_NEW_PASSWORD_NOT_INSERTED",
		USER_NEW_PASSWORD_INSERTED:"USER_NEW_PASSWORD_INSERTED",
		USER_DOESNT_EXIST:"USER_DOESNT_EXIST",
		USER_SESSION_EXPIRED:"USER_SESSION_EXPIRED",
		USER_POST_NOT_INSERTED:"USER_POST_NOT_INSERTED",
		USER_POST_INSERTED:"USER_POST_INSERTED",
		USER_PROFILE_NOT_UPDATED:"USER_PROFILE_NOT_UPDATED",
		USER_PROFILE_UPDATED:"USER_PROFILE_UPDATED"

	},
	Session : {
		Web_Prefix : 'UserId_'
	},
	ForgetPasswordMessages : {
		otpNumber:"_otpNumber",
		expiryTimer:180,
		InsertPasswordMessage:"NEW_PASSWORD_INSERTED",
		OTP_NOT_MATCHING:"OTP_NOT_MATCHING"
	},
	post:{
		POST_DELETED:"POST_DELETED",
		POST_NOT_EXISTED:"POST_NOT_EXISTED",
		POST_NOT_DELETED:"POST_NOT_DELETED"
	},
	friend:{
		SEND_FRIEND_REQUEST_NOT_SUCCESS:"SEND_FRIEND_REQUEST_NOT_SUCCESS",
		SEND_FRIEND_REQUEST_SUCCESS:"SEND_FRIEND_REQUEST_SUCCESS",
		SEND_FRIEND_REQUEST_ALREADY_SENT:"SEND_FRIEND_REQUEST_ALREADY_SENT",
		FRIEND_REQUEST_NOT_ACCEPTED:"FRIEND_REQUEST_NOT_ACCEPTED",
		FRIEND_REQUEST_ACCEPTED:"FRIEND_REQUEST_ACCEPTED",
		FRIEND_REQUEST_NOT_FOUND:"FRIEND_REQUEST_NOT_FOUND",
		FRIEND_REQUEST_NOT_REJECTED:"FRIEND_REQUEST_NOT_REJECTED",
		FRIEND_REQUEST_REJECTED:"FRIEND_REQUEST_REJECTED",
		FRIEND_NOT_REMOVED:"FRIEND_NOT_REMOVED",
		FRIEND_REMOVED:"FRIEND_REMOVED",
		FRIEND_NOT_FOUND:"FRIEND_NOT_FOUND"
	}
};
